package by.pvt.mapper;

import by.pvt.basic.Clients;
import by.pvt.basic.ClientsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    long countByExample(ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    int deleteByExample(ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    int insert(Clients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    int insertSelective(Clients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    List<Clients> selectByExample(ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    int updateByExampleSelective(@Param("record") Clients record, @Param("example") ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Jul 22 12:42:44 AST 2019
     */
    int updateByExample(@Param("record") Clients record, @Param("example") ClientsExample example);
}